name: Build & test
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025 ]
        framework: [ 'net8.0', 'net9.0' ]
        configuration: [ 'Debug', 'Release' ]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - run: dotnet restore
      - run: dotnet build --no-restore --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }}
      - run: dotnet test --no-build --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }}
        env:
          ALLURE_LABEL_env: "${{ matrix.os }}, ${{ matrix.framework }}, ${{ matrix.configuration }}"
      - uses: actions/upload-artifact@v4
        with:
          path: "./Allure.Examples.CiEnvs.Tests/bin/${{ matrix.configuration }}/${{ matrix.framework }}/allure-results"
          name: "AllureResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"

  generate-report:
    needs: build-test
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Check out Allure config
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            allurerc.mjs

      - name: Check out the report's branch
        uses: actions/checkout@v5
        with:
          # Use PAT so that the subsequent pushes trigger the publish-reports workflow
          token: ${{ secrets.GH_PAT }}
          ref: 'refs/tags/allure3-report-start'
          path: allure-report

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          pattern: AllureResults-*
          merge-multiple: true

      - name: Generate Allure report
        run: npx allure generate ./allure-results

        # We're uploading the report to a dedicated branch to merge it with Allure 2 version (see publish-reports.yml).
        # In real world, it can be uploaded directly to GitHub Pages from here.
      - name: Upload Allure 3 report
        working-directory: allure-report
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update the report"
          git push origin HEAD:allure3-report --force
